name: gpmobile
description: A new Flutter project.


publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.1.0

environment:
  # sdk: ">=2.2.0 <3.0.0"
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  animated_splash_screen: ^1.1.0
  animations: ^2.0.0
  beamer: ^0.14.0
  bloc: any
  bloc_pattern: ^2.2.3
  bubble: ^1.2.1
  carousel_slider: ^3.0.0
  clay_containers_plus: ^0.1.1+3
  configurable_expansion_tile: ^1.0.0
  cupertino_icons: ^1.0.0
  custom_navigation_bar: ^0.8.0
  custom_splash: ^0.0.2
  
  date_format: ^2.0.2
  day_night_switcher: ^0.2.0+1
  day_selector: ^1.0.0
  declarative_refresh_indicator: ^0.1.0
  desktop_window: ^0.4.0
  dynamic_themes: ^1.1.0
  equatable: ^2.0.3
  expandable: ^5.0.1
  expansion_card: ^0.1.0
  expansion_tile_card: ^2.0.0
  file_picker: ^3.0.1
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^2.0.2
  flutter_archive: ^4.0.1
  flutter_bloc: ^7.1.0
  flutter_cache_manager: ^2.0.0
  flutter_collapse: ^0.1.1
  flutter_conditional_rendering: ^2.0.0
  flutter_custom_clippers: ^1.1.2
  flutter_easyrefresh: ^2.2.1
  flutter_gen: ^3.1.1
  flutter_gifimage: ^1.0.1
  flutter_hooks: ^0.17.0
  flutter_icons: ^1.1.0
  flutter_mobx: ^2.0.0-nullsafety.3
  flutter_plugin_android_lifecycle: ^2.0.1
  flutter_screenutil: ^1.1.0
  flutter_search_bar: ^2.1.0
  flutter_slidable: ^0.5.7
  flutter_slidable_list_view: ^1.2.8
  flutter_spinkit: ^5.0.0
  font_awesome_flutter: ^9.1.0
  get: ^4.1.4
  google_fonts: ^1.1.0
  gradient_input_border: ^1.0.0
  gradients: ^0.1.1+1
  hidden_drawer_menu: ^3.0.0
  horizontal_data_table: ^3.0.0
  html: ^0.14.0
  http: ^0.12.0+4
  intl: ^0.17.0
  linked_scroll_controller: ^0.2.0
  launchers: ^0.5.6+1
  mobx: ^2.0.0-nullsafety.5
  multi_select_item: ^1.0.3
  month_picker_dialog: ^0.3.3
  open_file: any
  path: ^1.8.0
  path_provider: any
  peanut: ^4.0.1
  permission_handler: ^7.1.0
  plugin_platform_interface: ^2.0.0
  progress_dialog: ^1.2.2
  provider: any
  pull_to_refresh: ^1.6.5
  responsive: ^0.2.3+4
  responsive_builder: ^0.4.1
  responsive_framework: ^0.1.4
  responsive_widgets: ^2.0.1
  rflutter_alert: ^2.0.2
  rounded_tabbar_widget: ^0.0.2
  sprung: ^3.0.0
  shared_preferences: ^2.0.5
  simple_search_bar: ^0.1.7
  sliver_widget: ^0.5.0
  splashscreen: ^1.3.5
  sqflite: ^2.0.0+3
  stacked: ^2.2.2
  stacked_hooks: ^0.2.1
  syncfusion_flutter_pdf: ^18.3.53-beta
  share_plus: ^2.1.4
  table_calendar: ^2.3.3
  tutorial: ^1.0.7
  universal_html: ^1.2.4
  universal_io: ^2.0.3
  url_launcher: ^6.0.3
  validadores: ^1.0.2
  vertical_card_pager: ^1.0.3
  web_socket_channel: ^2.0.0
  r_get_ip: ^0.1.0
  dart_ipify: ^1.1.1
  universal_platform: ^1.0.0+1
  timer_button: ^2.0.0
  flutter_local_notifications: ^9.0.3
  flutter_native_timezone: ^2.0.0
  flutter_countdown_timer: ^4.1.0
  stop_watch_timer: ^0.6.0+1


dev_dependencies:
  build_runner: ^1.7.2
  build_web_compilers: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.0-nullsafety.2

  
flutter:

  uses-material-design: true

  assets:
    - images/
  #https://materialdesignicons.com/
flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: true